### ISSUE TITLE
Error: Missing file

### ISSUE THREAD

**Issue by wellkunnected** [tuanquanghpvn/BeeFly#1]
Hi!

I am getting an error message when trying to build the app:

error: /Users/Downloads/debussy.ttf: No such file or directory

**Comment by tuanquanghpvn** [comment]
Sory you can download font from http://www.dafont.com/debussy.font

**Comment by wellkunnected** [comment]
Where in the project do I add the file? Thanks for your help.

**Comment by tuanquanghpvn** [comment]
You can add file to root folder

**Comment by wellkunnected** [comment]
Hi,

I was able to add the file to the root folder and get the app to build and
run! My only issue now is that the menu button doesn't work when clicked.
Any suggestions here? Thanks for your help.

On Tue, Mar 22, 2016 at 8:59 PM, Trương Tuấn Quang <notifications@github.com

> wrote:
> 
> You can add file to root folder
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/tuanquanghpvn/BeeFly/issues/1#issuecomment-200098864

## 

Founded Well Kunnected, Inc 2010

**Comment by tuanquanghpvn** [comment]
@wellkunnected Ok. I push new commit to fix to. Currently, i disable font, you can pull it and run. Thanks.

**Comment by wellkunnected** [comment]
Awesome, thanks again for being a great help!
